/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db2entity.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Db2EntityDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/lmrc/db2entity/parser/antlr/internal/InternalDb2EntityDsl.tokens");
	}
}
