/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db2entity;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class Db2EntityDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.lmrc.db2entity.ui.internal.Db2EntityDslActivator.getInstance().getInjector("org.xtext.example.lmrc.db2entity.Db2EntityDsl");
	}
	
}
