/*
* generated by Xtext
*/
package org.xtext.example.lmrc.entityexpr.ui.contentassist;

import org.xtext.example.lmrc.entityexpr.ui.contentassist.AbstractEntityWithExprDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EntityWithExprDslProposalProvider extends AbstractEntityWithExprDslProposalProvider {

}
