/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db2entity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Db2EntityDslUiModule extends org.xtext.example.lmrc.db2entity.ui.AbstractDb2EntityDslUiModule {
	public Db2EntityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
