/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.uispec.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UispecDslUiModule extends org.xtext.example.lmrc.uispec.ui.AbstractUispecDslUiModule {
	public UispecDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
