/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.entity;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.example.lmrc.entity.naming.EntityDslNameProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDslRuntimeModule extends org.xtext.example.lmrc.entity.AbstractEntityDslRuntimeModule {
	
	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return EntityDslNameProvider.class;
	}

}
