/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DbDslRuntimeModule extends org.xtext.example.lmrc.db.AbstractDbDslRuntimeModule {

}
