<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="entityDsl" nsURI="http://www.xtext.org/example/lmrc/entity/EntityDsl"
    nsPrefix="entityDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//AbstractType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityReference" eSuperTypes="#//AbstractType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//Entity"/>
  </eClassifiers>
</ecore:EPackage>
