/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.uispec;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UispecDslRuntimeModule extends org.xtext.example.lmrc.uispec.AbstractUispecDslRuntimeModule {

}
