/*
* generated by Xtext
*/
package org.xtext.example.lmrc.entityexpr.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.lmrc.entityexpr.services.EntityWithExprDslGrammarAccess;

public class EntityWithExprDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EntityWithExprDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.lmrc.entityexpr.parser.antlr.internal.InternalEntityWithExprDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.lmrc.entityexpr.parser.antlr.internal.InternalEntityWithExprDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Module";
	}
	
	public EntityWithExprDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EntityWithExprDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
