/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DbDslUiModule extends org.xtext.example.lmrc.db.ui.AbstractDbDslUiModule {
	public DbDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
