/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db2entity.ui.contentassist;

import org.xtext.example.lmrc.db2entity.ui.contentassist.AbstractDb2EntityDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class Db2EntityDslProposalProvider extends AbstractDb2EntityDslProposalProvider {

}
