/*
* generated by Xtext
*/
package org.xtext.example.lmrc.uispec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class UispecDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/lmrc/uispec/parser/antlr/internal/InternalUispecDsl.tokens");
	}
}
