/*
* generated by Xtext
*/
package org.xtext.example.lmrc.uispec.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.lmrc.uispec.services.UispecDslGrammarAccess;

public class UispecDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private UispecDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.lmrc.uispec.parser.antlr.internal.InternalUispecDslParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.lmrc.uispec.parser.antlr.internal.InternalUispecDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Form";
	}
	
	public UispecDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UispecDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
