/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DbDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/xtext/example/lmrc/db/parser/antlr/internal/InternalDbDsl.tokens");
	}
}
