/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db.ui.contentassist;

import org.xtext.example.lmrc.db.ui.contentassist.AbstractDbDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DbDslProposalProvider extends AbstractDbDslProposalProvider {

}
