/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.entity.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityDslUiModule extends org.xtext.example.lmrc.entity.ui.AbstractEntityDslUiModule {
	public EntityDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
