/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db2entity.scoping;

import org.xtext.example.lmrc.db.scoping.DbDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class Db2EntityDslScopeProvider extends DbDslScopeProvider {

}
