/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.entityexpr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityWithExprDslUiModule extends org.xtext.example.lmrc.entityexpr.ui.AbstractEntityWithExprDslUiModule {
	public EntityWithExprDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
