/*
* generated by Xtext
*/
package org.xtext.example.lmrc.uispec.ui.contentassist;

import org.xtext.example.lmrc.uispec.ui.contentassist.AbstractUispecDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class UispecDslProposalProvider extends AbstractUispecDslProposalProvider {

}
