/*
* generated by Xtext
*/
package org.xtext.example.lmrc.entity;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EntityDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.lmrc.entity.ui.internal.EntityDslActivator.getInstance().getInjector("org.xtext.example.lmrc.entity.EntityDsl");
	}
	
}
