/*
* generated by Xtext
*/
package org.xtext.example.lmrc.db;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DbDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.lmrc.db.ui.internal.DbDslActivator.getInstance().getInjector("org.xtext.example.lmrc.db.DbDsl");
	}
	
}
