/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.entityexpr;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityWithExprDslRuntimeModule extends org.xtext.example.lmrc.entityexpr.AbstractEntityWithExprDslRuntimeModule {

}
