/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db2entity.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.lmrc.db2entity.ui.internal.Db2EntityDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class Db2EntityDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Db2EntityDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Db2EntityDslActivator.getInstance().getInjector(Db2EntityDslActivator.ORG_XTEXT_EXAMPLE_LMRC_DB2ENTITY_DB2ENTITYDSL);
	}
	
}
