/*
* generated by Xtext
*/
package org.xtext.example.lmrc.uispec;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class UispecDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.lmrc.uispec.ui.internal.UispecDslActivator.getInstance().getInjector("org.xtext.example.lmrc.uispec.UispecDsl");
	}
	
}
