/*
* generated by Xtext
*/
package org.xtext.example.lmrc.entity.ui.contentassist;

import org.xtext.example.lmrc.entity.ui.contentassist.AbstractEntityDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EntityDslProposalProvider extends AbstractEntityDslProposalProvider {

}
