/*
 * generated by Xtext
 */
package org.xtext.example.lmrc.db2entity;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Db2EntityDslRuntimeModule extends org.xtext.example.lmrc.db2entity.AbstractDb2EntityDslRuntimeModule {

}
